services:
 nginx:
     build: ./services/nginx
     container_name: nginx
     image: nginx:4mr0
     ports:
       - "4433:443"
     depends_on:
       - wordpress
       - mariadb
     volumes:
       - wpress:/var/www/html/wordpress
     networks:
       - containersNet
     restart: on-failure
 wordpress:
    build: ./services/wordpress
    container_name: wordpress
    image: wordpress:4mr0
    depends_on:
      - mariadb
    volumes:
      - wpress:/var/www/html/wordpress
    expose:
      - 9000
    networks:
      - containersNet
    env_file:
      - .env
    restart: on-failure
 mariadb:
    container_name: mariadb
    build: ./services/mariadb
    image: mariadb:4mr0
    env_file:
      - .env 
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - containersNet
    restart: on-failure
networks:
   containersNet:
     driver: bridge
volumes:
   wpress:
     name: wpress
     driver: local #docker stores the volume's data in a subdir under /var/lib/docker/volumes/db
     driver_opts:
       type: none
       device: /home/aamraouy/data/wp
       o: bind

   db:
     name: db
     driver: local #docker stores the volume's data in a subdir under /var/lib/docker/volumes/db
     driver_opts:
       type: none
       device: /home/aamraouy/data/testdb
       o: bind

