events {
}

http {
	server {
		listen 443 ssl;
		root /var/www/html/wordpress;
		index index.php index.html;
		ssl_certificate /etc/nginx/ssl/public.cert;
		ssl_certificate_key /etc/nginx/ssl/private.key;
		ssl_protocols TLSv1.2 TLSv1.3;
		server_name aamraouy.42.fr;
		location ~ \.php$ {
			fastcgi_index index.php;
			include fastcgi_params;
			fastcgi_pass wordpress:9000;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}
	}
}
