server{
	listen 443 ssl;
	root /var/www/html/wordpress;
	index index.php index.html;
	ssl_certificate /etc/nginx/ssl/public.cert;
	ssl_certificate_key /etc/nginx/ssl/private.key;
	ssl_protocols TLSv1.2 TLSv1.3;
	location ~ \.php${
		include fastcgi_params;
		fastcgi_pass wordpress:9000;
		fastcgi_index index.php;
	}
}
